# Generated by Django 4.0.4 on 2023-01-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0020_fighter_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muya_Thai_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=20)),
                ('padded_win', models.CharField(max_length=20)),
                ('padded_loose', models.CharField(max_length=20)),
                ('padded_draw', models.CharField(max_length=20)),
                ('armature_win', models.CharField(max_length=20)),
                ('armature_loose', models.CharField(max_length=20)),
                ('armature_draw', models.CharField(max_length=20)),
                ('professional_win', models.CharField(max_length=20)),
                ('professional_loose', models.CharField(max_length=20)),
                ('professional_draw', models.CharField(max_length=20)),
            ],
        ),
    ]
