# Generated by Django 4.0.4 on 2023-01-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0022_social_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='martial_art_record',
            old_name='Juzo_Experience',
            new_name='Judo_Experience',
        ),
        migrations.RenameField(
            model_name='martial_art_record',
            old_name='Juzo_Rank',
            new_name='Judo_Rank',
        ),
        migrations.RenameField(
            model_name='martial_art_record',
            old_name='Juzo_Style',
            new_name='Judo_Style',
        ),
        migrations.RenameField(
            model_name='martial_art_record',
            old_name='Juzo_Total',
            new_name='Judo_Total',
        ),
        migrations.RenameField(
            model_name='martial_art_record',
            old_name='Juzo_Win',
            new_name='Judo_Win',
        ),
    ]
