# Generated by Django 4.0.4 on 2023-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0024_alter_fighter_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='discipline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='fight_height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='fight_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='fight_weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='gym_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='height_units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fighter',
            name='wight_units',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
