# Generated by Django 4.0.4 on 2023-01-22 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0025_alter_fighter_discipline_alter_fighter_fight_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='fight_height',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='fight_name',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='fight_weight',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='gym_name',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='height_units',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wight_units',
        ),
        migrations.CreateModel(
            name='Additional_fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fight_name', models.CharField(max_length=100)),
                ('fight_weight', models.CharField(max_length=50)),
                ('wight_units', models.CharField(max_length=20)),
                ('fight_height', models.CharField(max_length=50)),
                ('height_units', models.CharField(max_length=20)),
                ('discipline', models.CharField(max_length=50)),
                ('gym_name', models.CharField(max_length=100)),
                ('fight_add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='combat_app.fighter')),
            ],
        ),
    ]
