# Generated by Django 4.0.4 on 2023-01-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0026_remove_fighter_discipline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Additional_fighter',
        ),
    ]
