# Generated by Django 4.0.4 on 2023-01-25 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0029_additional_fighter_fighter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivements',
            name='year',
        ),
    ]
