# Generated by Django 4.0.4 on 2023-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0031_achivements_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='discipline',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='fight_height',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='fight_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='fight_weight',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='fighter_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='gym_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='height_units',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fighter',
            name='wight_units',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Additional_fighter',
        ),
    ]
