# Generated by Django 4.0.4 on 2023-01-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('combat_app', '0032_fighter_discipline_fighter_fight_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter',
            name='fighter_name',
        ),
    ]
